name: Automated Tests

on: pull_request

jobs:
  jest:
    name: Jest Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/iron"

      - run: npm ci

      - run: npm test
